### ISSUE TITLE
package typed-ast older versions doesn't work on python 3.8?

### ISSUE THREAD

**Issue by marceloFA** [ethanchewy/PythonBuddy#61]
Hi, Ethan ✌ 
I just set PythonBuddy in my WSL installation and during the installation of the required packages an error was raised. I was able to fix it so I'm posting the step here in case anyone is interested.

1. Ubuntu 20.04 on Windows Subsystem  for Linux
2. Python 3.8
3. Clone the repo, create a virtualenv for it
4. Try to install the required packages and get the following error:
```console
    Running setup.py install for typed-ast ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tr7ufsax/typed-ast/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tr7ufsax/typed-ast/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qwpgruzh/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/marcelo/.local/include/python3.8/typed-ast
         cwd: /tmp/pip-install-tr7ufsax/typed-ast/
    Complete output (23 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/typed_ast
    copying typed_ast/__init__.py -> build/lib.linux-x86_64-3.8/typed_ast
    copying typed_ast/ast27.py -> build/lib.linux-x86_64-3.8/typed_ast
    copying typed_ast/ast3.py -> build/lib.linux-x86_64-3.8/typed_ast
    copying typed_ast/conversions.py -> build/lib.linux-x86_64-3.8/typed_ast
    running build_ext
    building '_ast27' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/ast27
    creating build/temp.linux-x86_64-3.8/ast27/Parser
    creating build/temp.linux-x86_64-3.8/ast27/Python
    creating build/temp.linux-x86_64-3.8/ast27/Custom
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iast27/Include -I/usr/include/python3.8 -c ast27/Parser/acceler.c -o build/temp.linux-x86_64-3.8/ast27/Parser/acceler.o
    ast27/Parser/acceler.c:13:10: fatal error: pgenheaders.h: No such file or directory
       13 | #include "pgenheaders.h"
          |          ^~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Expected behavior**
´´pip3 install -r should execute without errors´´

I managed to fix this by upgrading the version of the package that is being accused of raising the error. Someone at Stackoverflow had a [similar issue](https://stackoverflow.com/questions/59920177/cant-get-a-simply-django-app-to-build-on-docker-must-have-postgres-mysql-sup) and the solution worked for me here too. Solution:
> Upgrading to typed-ast==1.4.1 worked for me using Python 3.8.5

After the solution was applied I could install the required packages without errors.

**Comment by marceloFA** [comment]
This change actually broke two tests. Here's one of the two errors (both errors are the same):
```console
___________________________________ TestCodeRunning.test_if_file_created_and_deleted ___________________________________

self = <tests.test_app.TestCodeRunning testMethod=test_if_file_created_and_deleted>

    def test_if_file_created_and_deleted(self):
        """Test if the file will get created and deleted.
        :param self: instance of the current test.
        """
        with app.test_client() as test_client:

>           test_client.post('/check_code', data={
                "text": self.code_example
            })

tests/test_app.py:120:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../.local/lib/python3.8/site-packages/werkzeug/test.py:1039: in post
    return self.open(*args, **kw)
../.local/lib/python3.8/site-packages/flask/testing.py:196: in open
    return Client.open(
../.local/lib/python3.8/site-packages/werkzeug/test.py:993: in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
../.local/lib/python3.8/site-packages/werkzeug/test.py:884: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
../.local/lib/python3.8/site-packages/werkzeug/test.py:1119: in run_wsgi_app
    app_rv = app(environ, start_response)
../.local/lib/python3.8/site-packages/flask/app.py:2309: in __call__
    return self.wsgi_app(environ, start_response)
../.local/lib/python3.8/site-packages/flask_socketio/__init__.py:42: in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
../.local/lib/python3.8/site-packages/engineio/middleware.py:74: in __call__
    return self.wsgi_app(environ, start_response)
../.local/lib/python3.8/site-packages/flask/app.py:2295: in wsgi_app
    response = self.handle_exception(e)
../.local/lib/python3.8/site-packages/flask/app.py:1741: in handle_exception
    reraise(exc_type, exc_value, tb)
../.local/lib/python3.8/site-packages/flask/_compat.py:35: in reraise
    raise value
../.local/lib/python3.8/site-packages/flask/app.py:2292: in wsgi_app
    response = self.full_dispatch_request()
../.local/lib/python3.8/site-packages/flask/app.py:1815: in full_dispatch_request
    rv = self.handle_user_exception(e)
../.local/lib/python3.8/site-packages/flask/app.py:1718: in handle_user_exception
    reraise(exc_type, exc_value, tb)
../.local/lib/python3.8/site-packages/flask/_compat.py:35: in reraise
    raise value
../.local/lib/python3.8/site-packages/flask/app.py:1813: in full_dispatch_request
    rv = self.dispatch_request()
../.local/lib/python3.8/site-packages/flask/app.py:1799: in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
PythonBuddy/app.py:68: in check_code
    output = evaluate_pylint(text)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

text = 'for i in range(5):\n    print(i)\n'

    def evaluate_pylint(text):
        """Create temp files for pylint parsing on user code

        :param text: user code
        :return: dictionary of pylint errors:
            {
                {
                    "code":...,
                    "error": ...,
                    "message": ...,
                    "line": ...,
                    "error_info": ...,
                }
                ...
            }
        """
        # Open temp file for specific session.
        # IF it doesn't exist (aka the key doesn't exist), create one
        if "file_name" in session:
            f = open(session["file_name"], "w")
            for t in text:
                f.write(t)
            f.flush()
        else:
            with tempfile.NamedTemporaryFile(delete=False) as temp:
                session["file_name"] = temp.name
                for t in text:
                    temp.write(t.encode("utf-8"))
                temp.flush()

        try:
            ARGS = " -r n --disable=R,C"
            (pylint_stdout, pylint_stderr) = lint.py_run(
                session["file_name"] + ARGS, return_std=True)
        except Exception as e:
            raise Exception(e)

        if pylint_stderr.getvalue():
            print('Começa aqui')
            print(pylint_stderr.getvalue())
>           raise Exception("Issue with pylint configuration")
E           Exception: Issue with pylint configuration

PythonBuddy/app.py:146: Exception
```

And lastly, the actual output from ``pylint_stdrr.getvalue()`` was:
```console
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/marcelo/.local/lib/python3.8/site-packages/pylint/lint.py", line 75, in <module>
    import astroid
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/__init__.py", line 156, in <module>
    __import__(module[:-3])
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/brain/brain_builtin_inference.py", line 103, in <module>
    extend_builtins({'bytes': partial(_extend_str, rvalue="b''"),
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/brain/brain_builtin_inference.py", line 99, in extend_builtins
    transform(builtin_ast[class_name])
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/brain/brain_builtin_inference.py", line 84, in _extend_str
    fake = AstroidBuilder(MANAGER).string_build(code)['whatever']
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/builder.py", line 132, in string_build
    module = self._data_build(data, modname, path)
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/builder.py", line 173, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 162, in visit_module
    newnode.postinit([self.visit(child, newnode) for child in node.body])
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 162, in <listcomp>
    newnode.postinit([self.visit(child, newnode) for child in node.body])
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 174, in visit
    return visit_method(node, parent)
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 954, in visit_classdef
    return super(TreeRebuilder3, self).visit_classdef(node, parent,
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 394, in visit_classdef
    [self.visit(child, newnode)
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 394, in <listcomp>
    [self.visit(child, newnode)
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 174, in visit
    return visit_method(node, parent)
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 576, in visit_functiondef
    return self._visit_functiondef(nodes.FunctionDef, node, parent)
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 566, in _visit_functiondef
    body=[self.visit(child, newnode) for child in node.body],
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 566, in <listcomp>
    body=[self.visit(child, newnode) for child in node.body],
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 174, in visit
    return visit_method(node, parent)
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 741, in visit_return
    newnode.postinit(self.visit(node.value, newnode))
  File "/home/marcelo/.local/lib/python3.8/site-packages/astroid/rebuilder.py", line 172, in visit
    visit_method = getattr(self, visit_name)
AttributeError: 'TreeRebuilder3' object has no attribute 'visit_constant'

```

It seems that this is all related to package ``typed-ast``. At [their readme](https://github.com/python/typed_ast#python-38) they state that they're not planning on supporting py3.8 so the solution might be to use py3.7 or older

**Comment by ethanchewy** [comment]
Thank you for bringing this up and providing a thorough error report, plus linking a potential solution. 

This was very helpful. 

I am investigating this right now.

**Comment by ethanchewy** [comment]
@LeonardoFurtado lmk if pulling the most recent changes work! Thanks!

**Comment by ethanchewy** [comment]
@marceloFA  lmk if pulling the most recent changes work! Thanks!

I also updated the docs to reflect the specific virtualenv version you need.

**Comment by marceloFA** [comment]
Thank you for providing a solution to this so fast. Now I set up python 3.6.9 with asdf and all tests are passing.

**Comment by ethanchewy** [comment]
Wonderful - thanks for testing it and verifying. 

Really appreciate it!
